### ISSUE TITLE
Image Permissions from SSI book?

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/faq#2]
@peacekeeper can we get permission to include this image (with a link to the src of course) in the DIF FAQ?

![image](https://user-images.githubusercontent.com/37127325/116748222-f899c800-a9b3-11eb-923a-0b605b6bc339.png)

**Comment by peacekeeper** [comment]
@bumblefudge I think it was @talltree who created this particular image, and he as well as Alex Preukschat are more familar with the [book](https://www.manning.com/books/self-sovereign-identity) publication process and associated legal question, so you should ask them.

**Comment by talltree** [comment]
Yes, even though this image is in the Self-Sovereign Identity book, I originally created it for a slide deck on DID architecture for the W3C DID Working Group, so it is publicly available. So it is fine to use it.

**Comment by bumblefudge** [comment]
Thanks guys!
