### ISSUE TITLE
Adding a supplementary source to a question

### ISSUE THREAD

**Issue by vongohren** [decentralized-identity/faq#5]
I dont know how open or loose it is to adding a source of supplementary information.
But under: "Is it smart to try to make one agent/framework to rule them all?"

I have a very good presentation from Manu that talks about the work at SVIP. That goes into the mindset of locking effect, and why the include so many vendors into their work.

It can be found here: https://www.din.foundation/initiativ/tps-meeting-april

DIN has also now signed a partnership with DIF so there is some collaboration I guess

**Comment by bumblefudge** [comment]
Addressed in commit https://github.com/decentralized-identity/faq/commit/c19b9127b33882b3ab60c383eab14a8ea7bb1e13
